# Generated by Django 3.1.3 on 2021-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autorais_foto',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
