# Generated by Django 3.1.3 on 2021-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210113_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autorais_foto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tweet',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url_foto',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
