# Generated by Django 3.1.3 on 2021-01-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210118_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-id',)},
        ),
    ]
