# Generated by Django 3.1.3 on 2021-02-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210118_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ('noticia',)},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='reportagem_pt1',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='reportagem_pt2',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tweet',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url_foto',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
